### ISSUE TITLE
MinesweeperCell.isClose has no test

### ISSUE THREAD

**Issue by lbuttignol** [nmaguirre/minesweeper#125] opened 2016-09-01 22:57 UTC
MinesweeperCell.isClose should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by lbuttignol** [comment] 2016-09-01 23:16
Solve in this rev. 6c880aa

**Comment by saiema** [comment] 2016-09-06 20:07
A duplicate of #10 but that issue was never fully resolved.

**Closed by saiema** 2016-09-06 20:07 UTC
Labels: duplicate, resolved, Testing
