### ISSUE TITLE
MinesweeperCell.isBlocked missing

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/minesweeper#1] opened 2016-08-23 22:39 UTC
Method MinesweeperCell.isBlocked is missing from class MinesweeperCell. This method should report whether the cell is blocked or not. By default, a cell is not blocked.

**Comment by gabybertorello** [comment] 2016-08-23 23:22
MinesweeperCell.isBlocked implementada

**Comment by nricci** [comment] 2016-08-23 23:31
Please, supply the commit hash number in order to review you modifications more easily.

**Comment by gabybertorello** [comment] 2016-08-23 23:41
funcionalidad MinesweeperCell.isBlocked implementada (ed04daa)

**Comment by saiema** [comment] 2016-08-30 21:23
The issue is not fixed on ed04daa but it's resolved on af5d6ae along with the implementation of class MInesweeperCell.

Please always commit the minimum code that solves a specific issue.

**Closed by saiema** 2016-08-30 21:23 UTC
Labels: resolved
