### ISSUE TITLE
MinesweeperCell.hasMine has no tested

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/minesweeper#9] opened 2016-08-23 23:07 UTC
MinesweeperCell.hasMine should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by saiema** [comment] 2016-08-23 23:33
Missing description of the issue.

**Comment by fernando13** [comment] 2016-08-23 23:40
Ready ed04daa

**Comment by gamassimino** [comment] 2016-08-25 02:38
MinesweeperCellTest.hasMineTrue should not be `private`
please review this!

**Comment by adriangalfioni** [comment] 2016-08-25 18:43
@ezedepetris still missing the description of the issue.
@fernando13 missing @Test tag in "public void hasMineFalse()"

**Comment by ezedepetris** [comment] 2016-08-25 18:58
@adriangalfioni i create the issue when, i dont ready added to the project, then fernando take the issue before i add the description, so, i don't put the descriptions cause fernando take off me

**Comment by adriangalfioni** [comment] 2016-08-25 19:17
Ahh okok @ezedepetris, then all the work is to @fernando13 :sweat_smile:

**Comment by fernando13** [comment] 2016-08-25 21:50
MinesweeperCell.hasMine should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine

**Comment by fernando13** [comment] 2016-08-25 22:02
issue resolved in rev e536db7

**Comment by saiema** [comment] 2016-08-30 22:17
The issue is resolved in commit 04e44ee

**Closed by saiema** 2016-08-30 22:17 UTC
Labels: resolved
