### ISSUE TITLE
MinesweeperCell.isClose missing

### ISSUE THREAD

**Issue by camicalca** [nmaguirre/minesweeper#7] opened 2016-08-23 23:06 UTC

**Comment by saiema** [comment] 2016-08-23 23:34
Missing description of the issue.

**Comment by camicalca** [comment] 2016-08-24 01:14
Method MinesweeperCell.isClose is missing from class MinesweeperCell. This method should report whether the cell is close or not. By default, a cell is closed.

**Comment by nricci** [comment] 2016-08-25 21:26
@camicalca please provide the commit number that solved the issue

**Comment by saiema** [comment] 2016-08-30 21:57
The issue is resolved in fa3ddf4 but with an extra an unnecessary field isClosed.

**Closed by saiema** 2016-08-30 21:57 UTC
